### ISSUE TITLE
Only 1 slide moves even when slideMove is set to 'N'

### ISSUE THREAD

**Issue by jasins** [sachinchoolur/lightslider#118]
slideMove doesn't seem to be working. Initially I thought it might be something on my end, but then I noticed that the slider on Examples page is not responding to slideMove either.

The first example on:
http://sachinchoolur.github.io/lightslider/examples.html
This should move 2 slides on pressing the Next button (above 800 screenwidth). Its moving only 1 slide.

P.S. Great work btw :) Love the slider.
Thanks for your efforts.

**Comment by sachinchoolur** [comment]
Hi,
Multiple number of slidemove does not work with loop. It works only when loop is disabled. otherwise slidemove will be converted in to 1. I will work on lightslider after releasing lightGallery version 1.2.

I did't notice that loop was enabled in first example. Thank you for pointing this out.   I have updated demo website

**Comment by jasins** [comment]
That makes sense.
Thanks

**Comment by glukash** [comment]
Great piece of code. But more than one slide to move in loop mode would be nice.

**Comment by foinf** [comment]
Super late to the party but if you're using self hosted files (not CDN) then you can change 
`if ($(this).attr('class') === 'lSPrev') {
                            $el.goToPrevSlide();
                        } else {
                            $el.goToNextSlide();
                        }`

to

`if ($(this).attr('class') === 'lSPrev') {slider.goToSlide(slider.getCurrentSlideCount()-3);} else {slider.goToSlide(slider.getCurrentSlideCount()+3);}`

Change '3' to the number of slides you want it to slide.

**Comment by danavramescu** [comment]
> Super late to the party but if you're using self hosted files (not CDN) then you can change
> `if ($(this).attr('class') === 'lSPrev') { $el.goToPrevSlide(); } else { $el.goToNextSlide(); }`
> 
> to
> 
> `if ($(this).attr('class') === 'lSPrev') {slider.goToSlide(slider.getCurrentSlideCount()-3);} else {slider.goToSlide(slider.getCurrentSlideCount()+3);}`
> 
> Change '3' to the number of slides you want it to slide.

**IF YOU HAVE SELF HOSTED FILES:**
in order to keep things dynamic, and not force all your lightslider carousels to slide by the same hardcoded value (in your ex by 3 items at a time), then you can add a new custom setting , i called it customSlideMove default 1 , 

declare this property in the core js defaults
```
var defaults = {
        item: 3,
        autoWidth: false,
        ...
        customSlideMove: 1,
}
```


and change 

`if ($(this).attr('class') === 'lSPrev') {slider.goToSlide(slider.getCurrentSlideCount()-3);} else {slider.goToSlide(slider.getCurrentSlideCount()+3);}`
to
`{slider.goToSlide(slider.getCurrentSlideCount()-settings.customSlideMove);} else {slider.goToSlide(slider.getCurrentSlideCount()+settings.customSlideMove);}`

and in the initiation script declare your property:

```
 $("#slider").lightSlider({ 
            customSlideMove: 6,
 });
```


works for me this way with loop perfectly without creating unwanted sliding behaviour.
hope it helps
