### ISSUE TITLE
Getting li width when using autowidth and own li style

### ISSUE THREAD

**Issue by diogotoscano** [sachinchoolur/lightslider#154]
Instead of getting the li width + slideMargin, in lightslider.js on line 143 i change from:
w += (parseInt($children.eq(i).width()) + settings.slideMargin);
To:
w += (parseInt($children.eq(i).outerWidth()) + parseInt($children.eq(i).css('marginLeft')) + parseInt($children.eq(i).css('marginRight')));

Getting the outer width + the margins. With this the user can user dynamic sizes with padding + margin.
The old code was hidden/breaking the line with new li added dynamically.

**Comment by sachinchoolur** [comment]
Hi,
I think the better approach would be setting the padding/margin for any inner element.

ex:
``` html
<ul id="lightslider">
    <li>
        <div style="padding:0 10px; margin:0 20px;">
            your contents here
        </div>
    </li>
    <li>
        <div style="padding:0 10px; margin:0 20px;">
            your contents here
        </div>
    </li>
</ul
```
``` javascript
$('#lightslider').lightSlider();
```

**Comment by toddlevy** [comment]
Sorry for dredging up an old ticket, but I've got a situation where this solution isn't really tenable (that I can figure out).

In this case, the `<ul>` has display set to flex (to easily make all the inner items have the same height even if the content of some is shorter).

Then, each `<li>` except the last has a right border of 1px.

Because of this, the current calWidth function misses the width of the border, and comes up (n-1)px too narrow. (e.g. if 7 items with 1px border between them it'll be too narrow by 6px)

Adding a wrapper div inside the `<li>` and trying to set the border on that doesn't work because the border will only be as tall as the content of its given `<li>` and not the tallest `<li>` across all.

Any thoughts appreciated. Excellent tool overall.
