### ISSUE TITLE
Does not work with background images and text container

### ISSUE THREAD

**Issue by sebastiansulinski** [sachinchoolur/lightslider#79]
Very nice plugin, but I tried to use it with background images and unfortunately because of the way it obtains the height of the elements and the mass assignment of the absolute positioning within the container it didn't work.

**Comment by sachinchoolur** [comment]
Are you using fade mode?..
it would be helpful if you could provide a js fiddle demo..

**Comment by orosznyet** [comment]
Well, I got something similar.

I'm using the latest jQuery (1.11.1), Bootstrap (incl. JS), Google Fonts (Open Sans), FontAwesome (self hosted). The problem occurs only in Google Chrome and I think it must be related to a CSS processing delay. For some reason my theme CSS gets rendered after the document ready event has been triggered. So basically lightSlider init won't see the list item height in this case because it's not yet set. Changing the resource order might help, it solved the problem for me.

**Comment by sebastiansulinski** [comment]
Yes - I was trying it with the fade effect - sorry just came back from my hols - lots of emails. Will try to set up fiddle when I get a chance.

**Comment by em57** [comment]
I tried to pass a variable to the 'mode' option but bad luck. 
```
var modeEffect = (isIE8)? 'slide': 'fade';
....
mode : modeEffect,
......

**Comment by NicoleAbbott** [comment]
I have also tried to use a background image instead of using <img> but no luck - has this issue been resolved? Are there any solutions?
