### ISSUE TITLE
AutoPlay Pause/Stop on hover feature

### ISSUE THREAD

**Issue by ARCITEX** [sachinchoolur/lightslider#83]
hi, thanks for this great slider. +1 for this feature.
it's not unreachable with methods but i prefer this option be part of the main code.

i tried something like this and it's worked so far
slider.mouseover(function(){slider.pause()});
slider.mouseleave(function(){setTimeout(function(){slider.play()},4000)});

4000 is settings.pause

**Comment by sachinchoolur** [comment]
Hi,
As you said this can be easily done with the help of public methods. If anybody does not want this feature then this code will be waste for them. even if it is 4 lines of code. So that i did not included this feature in the main code. I have already demonstrated this on the example page.

But if it is difficult to find i can add this with the main code .
What do you think?

**Comment by ARCITEX** [comment]
thanks for the reply. yes you right, size of the plugin is important too. no problem, I've done this with methods (if you have any suggestion about a better way to accomplish this feature please let me know). Please keep this excellent plugin update and alive.
